# Default information for organization

name: datagood
title: DataGood
tagline: data science +
  social good.
logo: /images/datagood-logo.png
email: datagood@berkeley.edu
copyright: © 2023 DataGood at UC Berkeley
socials:
  - logo: /images/socials/facebook.png
    link: https://www.facebook.com/profile.php?id=61555245124236
    name: Facebook
  - logo: /images/socials/instagram.png
    link: https://www.instagram.com/datagoodberkeley/
    name: Instagram
  - logo: /images/socials/linkedin.png
    link: https://www.linkedin.com/groups/13889217/
    name: Linkedin
headers:
  - name: About
    link: /about
  - name: Team
    link: /team
  - name: Projects
    link: /projects
  - name: Events
    link: /events
  - name: Join
    link: /join
