name: datagood
title: Data Good
tagline: data science +
  social good.
logo: /images/heart-logo.png
email: datagood@berkeley.edu
socials:
  - logo: /images/facebook.png
    link: https://www.facebook.com/datagoodberkeley/
    name: Facebook
  - logo: /images/instagram.png
    link: https://www.instagram.com/datagoodberkeley/
    name: Instagram
  - logo: /images/linkedin.png
    link: https://www.linkedin.com/groups/13889217/
    name: Linkedin
  - logo: /images/github.png
    link: https://github.com/datagood-berkeley/
    name: Github
headers:
  - name: About
    link: /about
  - name: Team
    link: /team
  - name: Events
    link: /events
  - name: Education
    link: /education
  - name: Projects
    link: /projects
  - name: Contact
    link: /contact
