# Default information for organization

name: datagood
title: Data Good
tagline: data science +
  social good.
logo: /images/heart-logo.png
email: contact@datagood.berkeley.edu
copyright: © 2021 DataGood at UC Berkeley
socials:
  - logo: /images/socials/facebook.png
    link: https://www.facebook.com/datagoodberkeley/
    name: Facebook
  - logo: /images/socials/instagram.png
    link: https://www.instagram.com/datagoodberkeley/
    name: Instagram
  - logo: /images/socials/linkedin.png
    link: https://www.linkedin.com/groups/13889217/
    name: Linkedin
  - logo: /images/socials/github.png
    link: https://github.com/datagood-berkeley/
    name: Github
headers:
  - name: About
    link: /about
  - name: Team
    link: /team
  - name: Events
    link: /events
  - name: Projects
    link: /projects
  - name: Join
    link: /join
