- name: Juna Park
  position: Co-President
  image: "/images/team/juna-park.webp"
  Year: Senior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi! I’m Juna, a 4th-year Data Science major currently in my 6th semester with DataGood. You can usually find me at Bay Street watching a movie, eating malatang at Zhangliang, keeping up with college football (GO BEARS!), or shopping in Walnut Creek."
  socials:
    linkedin: https://www.linkedin.com/in/juna-park/
    coffee: https://calendly.com/junapark/datagood-coffee-chat-juna-park?month=2026-08

- name: Christine Xu
  position: Co-President
  image: "/images/team/christine-xu.webp"
  Year: Senior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "hello! im christine, a ds + econ 4th yr. i recently started crocheting, making bracelets, pickleballing, and laxing literally anywhere (not rly new). passionate about eating and watching whatever sport is on tv. if anyone has show recs pls let me know ive been searching… excited for this sem — lets all have some fun !!"
  socials:
    linkedin: https://www.linkedin.com/in/christine-xu-bba3a2255/
    coffee: https://calendly.com/christinexu05-berkeley/30min

- name: Esther Yang
  position: External Vice President
  image: "/images/team/esther-yang.webp"
  Year: Senior
  majors: Data Science, Statistics
  hobbies: N/A
  fun-fact: N/A
  bio: "hello, my name is esther and i'm a senior studying data science and economics. my professional interests include data analytics and product management, but outside of work, i love watching movies and going to the city!"
  socials:
    linkedin: https://www.linkedin.com/in/dh-estheryang/
    coffee: https://calendly.com/daheeyang/coffee-chat

- name: Katherine Ge
  position: Internal Vice President
  image: "/images/team/katherine-ge.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi! I'm Katherine, a junior studying Stats and Data science and the current IVP of DataGood. I love arts and crafts, snowboarding, music, fashion, movies, matcha, cats, and traveling."
  socials:
    linkedin: https://www.linkedin.com/in/katherinexge/
    coffee: https://calendly.com/katherine_ge-berkeley/datagoodcoffeechats

- name: Anderson Mao
  position: Co-VP of Projects
  image: "/images/team/anderson-mao.webp"
  Year: Junior
  majors: Data Science, Computer Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hey I'm Andy! I'm a Junior studying CS+DS and I'll be a VPP for DataGood this semester. I love to lift, play volleyball, play different instruments, and to talk about random topics. I love eating too :()"
  socials:
    linkedin: https://www.linkedin.com/in/andersonmao1/
    coffee: https://calendly.com/andersonmao-berkeley/anderson-mao-coffee-chat

- name: Tanushri Pinjala
  position: Co-VP of Projects
  image: "/images/team/tanushri-pinjala.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, I'm Tanushri! I'm a junior studying Data Science with an emphasis in Business Analytics, and I'm from the bay area. The areas of social good I'm passionate about include education, environmental sustainability, humanitarian aid, and financial literacy. In my free time, I love to read, build lego botanicals sets, binge-watch TV shows, and try new sweet treats!"
  socials:
    linkedin: https://www.linkedin.com/in/tanushri-pinjala/
    coffee: https://calendly.com/tanushri_pinjala-berkeley/datagood-berkeley-coffee-chat-tanushri

- name: Kennard Hou
  position: VP of Professional Development
  image: "/images/team/kennard-hou.webp"
  Year: Senior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "hi, i'm ken. i'm a senior studying data sci + stats, originally from Richland, WA but now living in the chicago burbs. I like a lot of things; pickleball, badminton, ping pong, poker, chess, board games, stonks & options, sitcoms, movies, eating, and i like trying new things. if u want to do something just ask, don't be shy, i will probably say yes or make up some excuse to say no"
  socials:
    linkedin: https://www.linkedin.com/in/kennardhou/
    coffee: https://calendly.com/kennard-berkeley/datagood-coffee-chat

- name: Mahika Bhan
  position: Co-VP of Social
  image: "/images/team/mahika-bhan.webp"
  Year: Sophomore
  majors: MCB, Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hey Everyone! I’m Mahi, a sophomore studying MCB and Data Science, originally from Portland, Oregon. I’m very passionate about beverages, and in my free time I love swimming/paddleboarding, singing with my a cappella group, cooking, playing volleyball, and taking digi flicks / creating vlogs. Please coffee chat me:) I'm more than willing to give advice or talk about anything!"
  socials:
    linkedin: https://www.linkedin.com/in/mahikabhan1
    coffee: https://calendly.com/mbhan-berkeley/30min

- name: Cooper Owen
  position: Co-VP of Social
  image: "/images/team/cooper-owen.webp"
  Year: Senior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi guys I'm Cooper, a senior from Southern California. This will be my 5th semester in DG, and I'm super excited to make it an awesome and memorable one as VP of Social. My social good interests are primarily in education and public policy causes, as well as throwing the most lit socials. Outside of school and DG, I'm super into movies, tv shows, Noah Kahan, and finding great food spots around the Bay. Feel free to coffee chat with me!"
  socials:
    linkedin: https://www.linkedin.com/in/cooper-owen-a8a24a28b/
    coffee: https://calendly.com/coopernowen-berkeley/datagood

- name: Ashley Xiao
  position: VP of Finance
  image: "/images/team/ashley-xiao.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, I'm Ashley! I'm a junior studying Economics and Data Science. I'm originally from Queens, NY, but I've lived in Scottsdale for most of my life. I LOVE a big bowl of fresh fruit, unnecessarily deep conversations, Diet Coke, and naps in the sun. My day gets exponentially better after a morning run, and I've found that writing poetry is an unpatched coping mechanism. If you’re reading this, I hope we get the chance to meet-- I’d love to hear about you!"
  socials:
    linkedin: https://www.linkedin.com/in/ashley-x-9590bb342/
    coffee: https://calendly.com/ashley-xiao

- name: Julina Vuong
  position: VP of Technology
  image: "/images/team/julina-vuong.webp"
  Year: Junior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "hi, i'm Julina! i'm from the bay and i love listening to music, raving, eating, sidequesting, and having fun with my friends. i'm so ready to meet all of you and make amazing memories this year!"
  socials:
    linkedin: https://www.linkedin.com/in/julinavuong/
    coffee: https://calendly.com/julinavuong-berkeley/dgcoffeechats

- name: Lawrenze Vigo
  position: VP of Outreach
  image: "/images/team/lawrenze-vigo.webp"
  Year: Junior
  majors: Data Science, Urban Studies
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi I'm Lawrenze! I'm a 3rd year studying Urban Studies and DS from San Jose, CA. I love public transit, singing with my a cappella group, iced americanos, matcha, and spicy food. You might see me around if you're a BayPass fan. I'm excited to meet you all this semester!!"
  socials:
    linkedin: https://www.linkedin.com/in/lawrenzevigo/
    coffee: https://calendly.com/lawrenze-berkeley/30min

- name: Paco Lau
  position: VP of Marketing
  image: "/images/team/paco-lau.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi! I'm Paco and a sophomore originally from Hong Kong. I'm passionate about the intersection of Data Science and Design and how data could be used for creative solutions for those in need. Beyond DataGood, I love playing tennis and collecting a bunch of small random desk decor."
  socials:
    linkedin: https://www.linkedin.com/in/pacolau/
    coffee: https://calendly.com/pacolau-berkeley/30min

- name: Adrian Nguyen
  position: Industry PM
  image: "/images/team/adrian-nguyen.webp"
  Year: Sophomore
  majors: EECS
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, I’m Adrian! I’m currently a sophomore studying data science. I love trying new cafes (to find my next lock in spot) going to the gym/bouldering, and playing racket sports like tennis, pickleball, etc."
  socials:
    linkedin: https://www.linkedin.com/in/adrian-nguyen124/
    coffee: https://calendly.com/adrianln124-berkeley/30min

- name: Sherry Shen
  position: Industry PM
  image: "/images/team/sherry-shen.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, I'm Sherry and I'm a sophomore majoring in Data Science and Economics. I am originally from Hong Kong. I am particularly interested in promoting equity through data-driven decisions. My interests outside of DG include solving sudoku, F1, and marching band. Feel free to ask me any questions about DataGood!"
  socials:
    linkedin: https://www.linkedin.com/in/sherry-shen-zl/
    coffee: https://calendly.com/sherryshenzl-berkeley/30min

- name: Athena Chen
  position: Industry PM
  image: "/images/team/athena-chen.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, I'm Athena! I'm a junior double majoring in Business and Data Science, and I'm from the Chicagoland area. I'm passionate about youth entrepreneurship, education, nonprofits, and financial literacy. I love anything related to crochet, junk journalling, hiking, and am always doing for a warm chocolate chip cookie!"
  socials:
    linkedin: https://www.linkedin.com/in/athenafangchen/
    coffee: https://calendly.com/athena-f-chen/30min

- name: Saransh Jain
  position: Industry PM
  image: "/images/team/saransh-jain.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hey! I'm Saransh, a junior from Fremont, CA studying Data Science and Economics. I'm interested in the intersections of data science with financial equity, economic policy, and social welfare. In my free time, I like to play pickleball, bike, watch football, make vegan desserts, and learn about architecture!"
  socials:
    linkedin: https://www.linkedin.com/in/saranshjain-/
    coffee: https://calendly.com/saranshjain-berkeley/datagood-coffee-chat

- name: Michael Birmingham
  position: Industry PM
  image: "/images/team/michael-birmingham.webp"
  Year: Junior
  majors: Data Science, Physics
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi I'm Michael, I'm a third year studying DS & physics and I'm an industry PM this semester. Looking forward to meeting everyone!"
  socials:
    linkedin: https://www.linkedin.com/in/michael-birmingham-cal/
    coffee: https://calendly.com/michael_birmingham-berkeley/datagood-coffee-chats

- name: Justin Fu
  position: Industry PM
  image: "/images/team/justin-fu.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hello. I'm Justin, a second-year student curious about how technology can be used to create  meaningful social impact. I've joined orgs here on campus like DataGood because I want to use the skills I've learned to help those who need it the most."
  socials:
    linkedin: https://www.linkedin.com/in/fu-justin7/
    coffee: https://calendly.com/jfu7171-berkeley/30min

- name: Vrajesh Daga
  position: Industry PM
  image: "/images/team/vrajesh-daga.webp"
  Year: Junior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "Hey, I'm Vrajesh! I'm a junior from Fremont studying Data Science and Econ and I'm passionate about harnessing AI/ML to make a positive impact in education. I love basketball, EDM, coffee, sudokus, TV shows (HIMYM, Ted Lasso, Breaking Bad, etc.), and food runs!"
  socials:
    linkedin: https://www.linkedin.com/in/vrajeshdaga/
    coffee: https://calendly.com/vrajeshdaga-berkeley/30min

- name: Jaylen Marshall
  position: Industry PM
  image: "/images/team/jaylen-marshall.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hey, my name is Jaylen Marshall and I’m a junior studying DS. I’m from San Fernando Valley in socal. I love volleyball, watching tv, singing, and playing video games."
  socials:
    linkedin: https://www.linkedin.com/in/jaylen-marshall-4b54a7324/
    coffee: https://calendly.com/jaylen115-berkeley/new-meeting

- name: Christine Ren
  position: Research PM
  image: "/images/team/christine-ren.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "hi! my name is christine ren, i’m a sophomore studying economics and data science. i grew up in hong kong but left for boarding school in oxford (uk) at 14- im passionate about finance, dj-ing, and reading. feel free to reach out :p"
  socials:
    linkedin: https://www.linkedin.com/in/christinerenbe/
    coffee: https://calendly.com/christineren-berkeley/30min

- name: Mirabelle Anderson
  position: Research PM
  image: "/images/team/mirabelle-anderson.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, I'm Mirabelle! I'm a sophomore from San Diego studying Data Science and Applied Math. I'm passionate about using data to make positive change, especially in healthcare and the environment. In my free time, I love playing soccer, flag football and pickleball, snowboarding, hiking, painting, embroidering (any crafts), and grabbing a coffee/boba."
  socials:
    linkedin: https://www.linkedin.com/in/mirabelle-anderson/
    coffee: https://calendly.com/mirabelle-berkeley

- name: Jillian Noblejas
  position: Research PM
  image: "/images/team/jillian-noblejas.webp"
  Year: Sophomore
  majors: Statistics
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, I’m Jillian! I am from the Bay Area and am majoring in Cognitive Science. I love going to concerts, watching the sunset, and grabbing a sweet treat with friends!"
  socials:
    linkedin: https://www.linkedin.com/in/jillian-rae-noblejas-301061381/
    coffee: http://calendly.com/jillian-r4e-berkeley

- name: Victor Chen
  position: Research PM
  image: "/images/team/victor-chen.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "Hi, my name is Victor, and I am a sophomore studying Data Science. I am passionate about social good and helping others. In my free time, I like exploring cafes/resturants, watching movies, and sewing. I also enjoy going to concerts, exploring SF, and being in nature."
  socials:
    linkedin: https://www.linkedin.com/in/victor-chen26/
    coffee: https://calendly.com/vhenc-berkeley/datagood-coffee-chat

