- name: First Last
  position: Position
  image: null
  socials:
    github: Link
- name: First Last
  position: Position
  image: null
  socials:
    github: Link
    linkedin: Link
- name: First Last
  position: Position
  image: null
  socials:
    github: Link
    linkedin: Link
    facebook: Link