- name: Saumya Choudhary
  position: External Projects Lead
  image: /images/team/saumya.jpg
  socials:
    linkedin: https://www.linkedin.com/in/saumya-choudhary-26893a186/

- name: Milleno Pan
  position: Internal Projects Lead
  image: /images/team/milleno.jpg
  socials:
    linkedin: https://www.linkedin.com/in/milleno-pan/

- name: Neha Hudait
  position: Outeach Technical Lead
  image: /images/team/neha.jpg
  socials:
    linkedin: https://www.linkedin.com/in/nehahudait/

- name: Andrew Huang
  position: Outreach Social Lead
  image: /images/team/andrew.jpg
  socials:
    linkedin: https://www.linkedin.com/in/andrew-huang-99b79519a/

- name: Elda Pere
  position: External Project Manager
  image: /images/team/elda.jpg
  socials:
    linkedin: https://www.linkedin.com/in/elda-pere/

- name: Kiernynn Grantham-Crum
  position: External Project Manager
  image: /images/team/kiernynn.jpg
  socials:
    linkedin: https://www.linkedin.com/in/kiernynn-gc/

- name: Pavan Gowda
  position: External Project Manager
  image: /images/team/pavan.png
  socials:

- name: Gloria Zhang
  position: Internal Project Manager
  image: /images/team/none.png
  socials:

- name: Isabella Borkovic
  position: Internal Project Manager
  image: /images/team/isabella.png
  socials:
    linkedin: https://www.linkedin.com/in/isabella-borkovic-8a921534/

- name: Shani Lyubomirsky
  position: Outreach Technical
  image: /images/team/shani.png
  socials:
    linkedin: https://www.linkedin.com/in/shani-lyubomirsky-9583bb198/

- name: Wilson Nguyen
  position: Outreach Technical
  image: /images/team/wilson.jpg
  socials:
    github: https://github.com/potatoparser/
    linkedin: https://www.linkedin.com/in/wilson-nguyen-4252b9163/

- name: Ashritha Eswaran
  position: Outreach Social
  image: /images/team/ashritha.jpg
  socials:
    linkedin: https://www.linkedin.com/in/ashritha-e-703aba134/

- name: Molisha Shah
  position: Outreach Social
  image: /images/team/molisha.png
  socials:
    linkedin: https://www.linkedin.com/in/molishashah/
