- name: Juna Park
  position: Co-President
  image: "/images/team/juna-park.webp"
  Year: Senior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/juna-park/
    coffee: N/A

- name: Christine Xu
  position: Co-President
  image: "/images/team/christine-xu.webp"
  Year: Senior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/christine-xu-bba3a2255/
    coffee: N/A

- name: Esther Yang
  position: External Vice President
  image: "/images/team/esther-yang.webp"
  Year: Junior
  majors: Data Science, Statistics
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/dh-estheryang/
    coffee: N/A

- name: Katherine Ge
  position: Internal Vice President
  image: "/images/team/katherine-ge.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/katherinexge/
    coffee: N/A

- name: Anderson Mao
  position: Co-VP of Projects
  image: "/images/team/anderson-mao.webp"
  Year: Junior
  majors: Data Science, Computer Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/andersonmao1/
    coffee: N/A

- name: Tanushri Pinjala
  position: Co-VP of Projects
  image: "/images/team/tanushri-pinjala.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/tanushri-pinjala/
    coffee: N/A

- name: Kennard Hou
  position: VP of Professional Development
  image: "/images/team/kennard-hou.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/kennardhou/
    coffee: N/A

- name: Mahika Bhan
  position: Co-VP of Social
  image: "/images/team/mahika-bhan.webp"
  Year: Sophomore
  majors: MCB, Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/mahikabhan1
    coffee: N/A

- name: Cooper Owen
  position: Co-VP of Social
  image: "/images/team/cooper-owen.webp"
  Year: Senior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/cooper-owen-a8a24a28b/
    coffee: N/A

- name: Ashley Xiao
  position: VP of Finance
  image: "/images/team/ashley-xiao.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/ashley-x-9590bb342/
    coffee: N/A

- name: Julina Vuong
  position: VP of Technology
  image: "/images/team/julina-vuong.webp"
  Year: Junior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/julinavuong/
    coffee: N/A

- name: Lawrenze Vigo
  position: VP of Outreach
  image: "/images/team/lawrenze-vigo.webp"
  Year: Junior
  majors: Data Science, Urban Studies
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/lawrenzevigo/
    coffee: N/A

- name: Paco Lau
  position: VP of Marketing
  image: "/images/team/paco-lau.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/pacolau/
    coffee: N/A

- name: Adrian Nguyen
  position: Industry PM
  image: "/images/team/adrian-nguyen.webp"
  Year: Sophomore
  majors: EECS
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/adrian-nguyen124/
    coffee: N/A

- name: Sherry Shen
  position: Industry PM
  image: "/images/team/sherry-shen.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "HN/A"
  socials:
    linkedin: https://www.linkedin.com/in/sherry-shen-zl/
    coffee: N/A

- name: Athena Chen
  position: Industry PM
  image: "/images/team/athena-chen.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/athenafangchen/
    coffee: N/A

- name: Saransh Jain
  position: Industry PM
  image: "/images/team/saransh-jain.webp"
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/saranshjain-/
    coffee: N/A

- name: Michael Birmingham
  position: Industry PM
  image: "/images/team/michael-birmingham.webp"
  Year: Junior
  majors: Data Science, Physics
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/michael-birmingham-cal/
    coffee: N/A

- name: Justin Fu
  position: Industry PM
  image: "/images/team/justin-fu.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/fu-justin7/
    coffee: N/A

- name: Vrajesh Daga
  position: Industry PM
  image: "/images/team/vrajesh-daga.webp"
  Year: Junior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/vrajeshdaga/
    coffee: N/A

- name: Jaylen Marshall
  position: Industry PM
  image: "/images/team/jaylen-marshall.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: ""
  socials:
    linkedin: https://www.linkedin.com/in/jaylen-marshall-4b54a7324/
    coffee: N/A

- name: Christine Ren
  position: Research PM
  image: "/images/team/christine-ren.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/christinerenbe/
    coffee: N/A

- name: Mirabelle Anderson
  position: Research PM
  image: "/images/team/mirabelle-anderson.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/mirabelle-anderson/
    coffee: N/A

- name: Jillian Noblejas
  position: Research PM
  image: "/images/team/jillian-noblejas.webp"
  Year: Sophomore
  majors: Statistics
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/jillian-rae-noblejas-301061381/
    coffee: N/A

- name: Victor Chen
  position: Research PM
  image: "/images/team/victor-chen.webp"
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: "N/A"
  socials:
    linkedin: https://www.linkedin.com/in/victor-chen26/
    coffee: N/A

