- name: Saumya Choudhary
  position: President
  image: /images/team/saumya.png
  socials:
    linkedin: https://www.linkedin.com/in/saumya-choudhary-26893a186/
- name: Neha Hudait
  position: President
  image: /images/team/neha.png
  socials:
    linkedin: https://www.linkedin.com/in/nehahudait/
- name: Pulkit Bhasin
  position: External VP
  image: /images/team/pulkit.png
  socials:
    linkedin: https://www.linkedin.com/in/pulkit-bhasin-7a6026197/

- name: Andrew Huang
  position: Internal VP
  image: /images/team/andrew.png
  socials:
    linkedin: https://www.linkedin.com/in/andrew-huang-99b79519a/

- name: Ashritha Eswaran
  position: VP Education
  image: /images/team/ashritha.png
  socials:
    linkedin: https://www.linkedin.com/in/ashritha-e-703aba134/

- name: Milleno Pan
  position: VP Finance
  image: /images/team/milleno.png
  socials:
    linkedin: https://www.linkedin.com/in/milleno-pan/

- name: Wilson Nguyen
  position: Webmaster
  image: /images/team/wilson.png
  socials:
    github: https://github.com/potatoparser/
    linkedin: https://www.linkedin.com/in/wilson-nguyen-4252b9163/

- name: Elda Pere
  position: Project Manager
  image: /images/heart-thumbnail.png

- name: Calvin Chen
  position: Project Manager
  image: /images/heart-thumbnail.png

- name: Kiernynn Grantham-Crum
  position: Content Writer
  image: /images/heart-thumbnail.png
