#headline: "Our Mission"
text: "DataGood @ Berkeley empowers the next generation of changemakers to harness data science for social impact. Since 2020, our student-led organization has enabled 80+ members to design, develop, and deliver real-world projects that drive positive change by partnering with mission-driven organizations to turn data into action for the public good."
highlights:
  - number: "73%"
    label: "women in leadership"
  - number: "12"
    label: "semesters in operation"
  - number: "26"
    label: "industry projects"
  - number: "32"
    label: "research projects"
