# This configuration is used for the pages on the website
# The pages of each route is by default, set to the route itself, ie: /about -> about, /about/wilson -> about-wilson, etc.
# Changing pages does not change the header navigation bar. To do that, modify /configs/default.yml

/:
  page: home

/mission:
  title: our mission.
  mission: mission.yml

/values:
  title: our values.
  values: values.yml

/culture:
  title: our culture.
  culture: culture.yml

/careers:
  title: where we end up.
  careers: careers.yml

/team:
  title: meet the team.
  members: members.yml

/education:
  title: education.
  topics: topics.yml

/projects:
  title: projects.
  projectGroups: projects.yml

/join:
  title: join us.