- link: https://gspp.berkeley.edu/centers/cepp/projects/mapping-for-environmental-justice
  title: Mapping for Environmental Justice
  description: Mapping for Environmental Justice (MEJ) is an initiative to create interactive and publicly-accessible maps displaying environmental justice data for individual states. With guidance from the residents of impacted communities, MEJ combines environmental, public health, and demographic data into an indicator of vulnerability for communities in every state.
  image: images/projects/mapping.png
  color: green

- link: https://docs.google.com/presentation/d/1srR26ON6Vu-ygoowqm9AqW7AJcM6NW0Y03QRXd-njM4/edit#slide=id.g8292d9be50_0_1663
  title: Electronic Pathology Report Classification
  description: We were tasked by the Cancer Registry of Greater California to use ML and NLP on electronic pathology records to identify reports missing critical diagnostic information. The purpose of this project was to improve the quality of information available to physicians treating bladder cancer and save hundreds of lives in California patients who are disproportionately of African American, South Asian, Japanese and non-Hispanic backgrounds
  image: images/projects/pathology.png
  color: pink
