# Configuration for all projects

# TODO copy paste for spring 2023 research and industry projects

# - title: spring 2023 industry projects
#   projects:
#     - link:
#       title: TBA
#       description: 
#       color: blue
#       image: 
#     - link:
#       title: TBA
#       description: 
#       color: pink
#       image: 

- title: spring 2023 research projects
  projects:
    - link: 
      title: Analysis of Education Equality and Income
      description: 
      image: /images/projects/detection.webp
      color: yellow
    - link:
      title: Analysis of Pandemic and Unemployment
      description: 
      image:  /images/projects/sentiment.webp
      color: green
    - link: 
      title: Cancer Detection with Data Analysis
      description: 
      image: /images/projects/unemployment.webp
      color: blue


- title: fall 2022 industry projects
  projects:
    - link:
      title: Community Resources for Science (CRS)
      description: The main goal of this project is to help the Community Resources for Science (CRS) analyze survey data from 10+ years of surveys stored in CSV files, possibly selecting only certain years to look at. CRS anticipates looking at 6-8 key questions like teachers who are newer vs more experienced; teachers from 3 different school districts, teachers' level of confidence and amount of time spent on teaching science, etc. The primary reason for looking more into these key questions is to help CRS better understand the trends and differentiations among these key questions. 
      color: blue
      image: /images/projects/crs.webp
    - link:
      title: Food Bank of Contra Costa & Solano
      description: The main goal for this project is to help the Food Bank of Contra Costa & Solano better understand the communities they are serving. In order to accomplish this, we will add layers to the existing Tableau dashboard that is currently being used to map and visualize food distribution and needs. Adding more demographic layers to the map will allow the Food Bank of Contra Costa & Solano to better understand what specific communities they are reaching. Additionally, we would help analyze impact through more detailed visualizations in a dashboard. 
      color: pink
      image: /images/projects/fbccs.webp

- title: fall 2022 research projects
  projects:
    - link: 
      title: Tracking Causes of Climate Change
      description: 'This project focuses on using data science methods such as data visualization, regression, and classification to identify and predict fraudulent entries in healthcare provider data. Suggested prereq: Data 8'
      image: /images/projects/anomaly.webp
      color: yellow
    - link:
      title: COVID sentiment analysis using NLP
      description: 'As we move into a world that has seen the numerous waves of COVID-19, we want to learn more about how people have adjusted to the global pandemic we are enduring. Topics of interest include: mental health, healthcare, politics, vaccines, employment etc.'
      image:  /images/projects/sentiment.webp
      color: green
    - link: 
      title: Unemployment Rate Analysis
      description: 'The goal of this project is to utilize multiple datasets to learn important techniques in data science, and educate students on how to provide clear, presentable data. The final project will use datasets on the general US unemployment rate from 1948 to 2022 and more detailed percentages classified based on age, race, education level.'
      image: /images/projects/unemployment.webp
      color: blue
    - link:
      title: Gender Income Inequality
      description: 'The goal of this project is to utilize multiple datasets to learn important techniques in data science, and educate students on how to provide clear, presentable data. The final project will use datasets on the income of men and women in various tech jobs where members will be taking a look at how various factors such as seniority, level of education and age can contribute to gender inequality in income.'
      image: /images/projects/inequality.webp
      color: purple

- title: spring 2022 industry projects
  projects:
    - link:
      title: Interactive Map to Detect Environmental Inequities in Communities
      description: This project is an interactive map that layers data about demographics and environmental issues to detect inequities between communities.
      color: blue
      image: /images/projects/waternow.webp
    - link: 
      title: Anomaly Detection in Healthcare Providers
      description: 'This project focuses on utilizing data science techniques such as data visualization and exploratory data analysis to find trends in climate data. We will examine the factors which affect the Earth’s temperature in various locations.'
      image: /images/projects/detection.webp
      color: yellow
    - link:
      title: NMDC
      description: This project will contribute to the NMDC's sample-annotator API for repairing biosample metadata that doesn't adhere to standards like MIxS. The repaired data will drive collaboration and open science.
      color: pink
      image: /images/projects/nmdc.webp

- title: spring 2022 research projects
  projects:
    - link:
      title: Climate Change Data Analysis
      description: 'This project aims to create a model to predict future CO2 levels globally, or other indicators of climate change, while reviewing important packages and tools for analyzing and visualizing data. Suggested prereq: Data 8'
      image:  /images/projects/climate.webp
      color: green
    - link: 
      title: Online Learning Effect on Student Performance
      description: 'This project aims to understand the effects of online learning on student performance. Using important data science techniques such as regression, we will look at how various factors affect student performance in both online and in-person learning environments. Suggested prereq: Data 8'
      image: /images/projects/online.webp
      color: blue
    - link:
      title: Tracking COVID-19 Vaccine Equity
      description: 'In this project, we aim to employ national vaccination data to analyze COVID-19 vaccination programs in different countries. We would like to answer important questions about how the world is dealing with the surging virus. Do richer and poorer countries have very differing access to COVID-19 vaccines? Which country has the most efficient vaccination program? Does the type of vaccine being used matter? Or are there any geopolitical factors in play? Thanks to the comprehensive dataset from Our World in Data (OWID), there’s plenty of room for us to track COVID-19 vaccine equity across the globe.
Difficulty level: Easy to medium. Will cover the basics of everything. No prior technical experience required.'
      image: /images/projects/tracking.webp
      color: purple

- title: fall 2021 industry projects
  projects:
    - link:
      title: Student Classifier
      description: This project is a web application that Downtown College Prep can utilize to improve English learner reclassification and cohort identification for their students.
      image: /images/heart-logo.png
      color: purple
    - link:
      title: Ocean Trash Dashboard
      description: This project is a live dashboard with Pacifica Beach Coalition clean up data that’s deployed online for progress tracking  and education.
      image: /images/heart-logo.png
      color: blue

- title: fall 2021 research projects
  projects:
    - link:
      title: Bay Area Public and Environmental Health Analysis
      description: This project aims to introduce a variety of packages essential to analyzing and visualizing data, as well as exploring different sectors of social good.
      image: /images/heart-logo.png
      color: purple
    - link:
      title: COVID-19 Sentiment Analysis
      description: This project aims to use sentiment analysis on tweets about the COVID-19 vaccination to understand how people feel about it across the world.
      image: /images/heart-logo.png
      color: pink
    - link:
      title: World Happiness Report
      description: This project is to understand data about the World Happiness Report and what factors impact global wellbeing.
      image: /images/heart-logo.png
      color: yellow


- title: spring 2021 industry projects
  projects:
  - link: https://www.facebook.com/UC-Berkeley-SAFE-Chatbot-102005888779715
    title: Firewatch Chatbot
    description: "The Firewatch Chatbot aims to: provide reliable info on fires close by, answer fire preparedness questions, and aid CalSAFE’s donor engagement and outreach"
    image: /images/projects/fire.webp
    color: yellow
  - link: https://www.ptk.org/
    title: Transfer Student Classification
    description: Building an NLU topic model using over 10 years of scholarship submissions to both identify the problems students speak about in an unsupervised manner and analyze growth and evolution of them in time-series text data.
    image: /images/projects/transfer.webp
    color: purple

- title: spring 2021 research projects
  projects:
  - link:
    title: DC + Chicago Crime Analysis
    description: Leveraging DC + Chicago crime data to visualize trends across factors such as race, socioeconomic status using regression and geospatial analysis
    image: /images/projects/crime.webp
    color: pink
  - link:
    title: Natural Language Processing on US Legislature
    description: This project aims to analyze Pennsylvania legislature using NLP techniques such as TF-IDF, Part of Speech tagging, and more
    image: /images/projects/legislature.webp
    color: yellow
  - link:
    title: Cardiovascular Disease Classifer
    description: Building a classifer to predict various severities of cardiovascular disease in patients
    image: /images/projects/disease.webp
    color: pink

- title: past projects
  projects:
  - link: https://ng-usa.org/
    title: Nehemiah Gateway USA
    description: Provide actionable information that will increase donor reach and engagement using data science and NLP
    image: /images/projects/nehemiah_gateway.webp
    color: yellow

  - link: https://uc-ciee.org/
    title: California Institute For Energy And Environment
    description: Exploring racial biases/implications in solar energy and equity with respect to credit score data
    image: /images/projects/ciee.webp
    color: blue

  - link:
    title: Medical Insurance Analysis and Classifer
    description: Created data science project that utilized a Python GUI to visualize different data science techniques on insurance health charges data using Pandas, Sklearn, and Tkinter
    image: /images/projects/insurance.webp
    color: green

  - link: https://gspp.berkeley.edu/centers/cepp/projects/mapping-for-environmental-justice
    title: Mapping for Environmental Justice
    description: Mapping for Environmental Justice (MEJ) is an initiative to create interactive and publicly-accessible maps displaying environmental justice data for individual states. With guidance from the residents of impacted communities, MEJ combines environmental, public health, and demographic data into an indicator of vulnerability for communities in every state.
    image: /images/projects/mapping.webp
    color: green

  - link: https://docs.google.com/presentation/d/1srR26ON6Vu-ygoowqm9AqW7AJcM6NW0Y03QRXd-njM4/edit#slide=id.g8292d9be50_0_1663
    title: Electronic Pathology Report Classification
    description: In partnership with the Cancer Registry of Greater California, this project uses ML and NLP on electronic pathology records to identify reports missing critical diagnostic information especially for ethinic minorities in the state of California.
    image: /images/projects/pathology.webp
    color: pink
