- title: spring 2021 external projects
  projects:
  - link: /404
    title: Firewatch Chatbot
    description: "The Firewatch Chatbot aims to: provide reliable info on fires close by, answer fire preparedness questions, and aid CalSAFE’s donor engagement and outreach"
    image: /images/projects/fire.webp
    color: yellow
  - link: /404
    title: Anonymous Company
    description: The company would like to stay anonymous. This project entails building a classifier to predict agriculture needs.
    image: /image/projects/classified.webp
    color: blue
- title: spring 2021 internal projects
  projects:
  - link: /404
    title: DC + Chicago Crime Analysis
    description: Leveraging DC + Chicago crime data to visualize trends across factors such as race, socioeconomic status using regression and geospatial analysis
    image: /images/projects/crime.webp
    color: pink
  - link: /404
    title: Natural Language Processing on US Legislature
    description: This project aims to analyze Pennsylvania legislature using NLP techniques such as TF-IDF, Part of Speech tagging, and more
    image: /images/projects/legislature.webp
    color: yellow
  - link: /404
    title: Cardiovascular Disease Classifer
    description: Building a classifer to predict various severities of cardiovascular disease in patients
    image: /images/projects/disease.webp
    color: pink

- title: past projects
  projects:
  - link: /404
    title: Nehemiah Gateway USA
    description: Provide actionable information that will increase donor reach and engagement using data science and NLP
    image: /images/projects/nehemiah_gateway.webp
    color: yellow

  - link: /404
    title: California Institute For Energy And Environment
    description: Exploring racial biases/implications in solar energy and equity with respect to credit score data
    image: /images/projects/ciee.webp
    color: blue

  - link: /404
    title: Medical Insurance Analysis and Classifer
    description: Created data science project that utilized a Python GUI to visualize different data science techniques on insurance health charges data using Pandas, Sklearn, and Tkinter
    image: /images/projects/insurance.webp
    color: green

  - link: https://gspp.berkeley.edu/centers/cepp/projects/mapping-for-environmental-justice
    title: Mapping for Environmental Justice
    description: Mapping for Environmental Justice (MEJ) is an initiative to create interactive and publicly-accessible maps displaying environmental justice data for individual states. With guidance from the residents of impacted communities, MEJ combines environmental, public health, and demographic data into an indicator of vulnerability for communities in every state.
    image: /images/projects/mapping.webp
    color: green

  - link: https://docs.google.com/presentation/d/1srR26ON6Vu-ygoowqm9AqW7AJcM6NW0Y03QRXd-njM4/edit#slide=id.g8292d9be50_0_1663
    title: Electronic Pathology Report Classification
    description: In partnership with the Cancer Registry of Greater California, this project uses ML and NLP on electronic pathology records to identify reports missing critical diagnostic information especially for ethinic minorities in the state of California.
    image: /images/projects/pathology.webp
    color: pink
