# This configuration is used for the redirects on the website

/zoom: https://berkeley.zoom.us/j/98351933735?pwd=dE0yeEl5OEZyd05MOC9VbWxKOXUxQT09
/discord: https://discord.com/invite/j6WDA75k7s
/mtm: https://tinyurl.com/y3qqkdnl
