# This configuration is used for the redirects on the website

/zoom: https://berkeley.zoom.us/meeting/register/tJwucuihrTgtGdEQb-M4EfHDkByHwUxEr1Ki
/discord: https://discord.com/invite/j6WDA75k7s
/mtm: https://tinyurl.com/y3qqkdnl
