# This configuration is used for the redirects on the website

/zoom: https://berkeley.zoom.us/meeting/register/tJwucuihrTgtGdEQb-M4EfHDkByHwUxEr1Ki
/discord: https://discord.com/invite/j6WDA75k7s
/mtm: https://tinyurl.com/y3qqkdnl
/infosession: https://berkeley.zoom.us/rec/play/Enjk_qBe4sFx4l3IVPhJxoyGYKSMow-gwWJGicuHId48V4OSb_ZjcdyUXPASUyX_snu6gKEGL5uX-Q.o4klYKQD9NxNmL6Z
/welcomenight: https://berkeley.zoom.us/meeting/register/tJArfu2tqjIvHteo4RCE13DDAlfBdizWdUYV
