# This configuration is used for the redirects on the website

/zoom: https://berkeley.zoom.us/meeting/register/tJwucuihrTgtGdEQb-M4EfHDkByHwUxEr1Ki
/discord: https://discord.gg/N4sesghbZN
/mtm: https://tinyurl.com/y3qqkdnl
/infosession: https://drive.google.com/file/d/1m0-OlESjMM-dX3UEhSYoLRQDyB3HzJjm/view?fbclid=IwAR3dJ0kMcCxOcn2eZhUSDGtyNje4k4HYe1STBJq71vAmmMli5z2TfCFMiws
/welcomenight: https://berkeley.zoom.us/meeting/register/tJArfu2tqjIvHteo4RCE13DDAlfBdizWdUYV
