# This configuration is used for the redirects on the website

# custom redirects are create with /blank
/zoom: https://berkeley.zoom.us/meeting/register/tJwucuihrTgtGdEQb-M4EfHDkByHwUxEr1Ki
/discord: https://discord.gg/KyhSB9c9um
/mtm: https://tinyurl.com/y3qqkdnl
/infosession: https://drive.google.com/file/d/1JOmQjK5OQskeCq1yQ4uftXqPMYldw1jX/view?usp=sharing
/welcomenight: https://berkeley.zoom.us/meeting/register/tJArfu2tqjIvHteo4RCE13DDAlfBdizWdUYV
/datathon: https://ibmzdatathon-cal.com/