- link: https://data.berkeley.edu/
  image: /images/sponsors/divisionnew.webp

- link: https://dlab.berkeley.edu/
  image: /images/sponsors/dlab.webp

- link: https://data.berkeley.edu/research/discovery-program-home
  image: /images/sponsors/discovery.webp

- link: https://bigideascontest.org/
  image: /images/sponsors/bigideas.webp

- link: https://schmidtfutures.com/
  image: /images/sponsors/schmidt.webp
