- date: 9/15 - 9/21
  title: NO LECTURE
  lab:
  webcast:

- date: 9/22 - 9/28
  title: Introduction to Data Science, Social Good, Python Visualization
  lab: Link
  webcast: Link

- date: 9/29 - 10/5
  title: Linear Regression and Regularization
  lab: Link
  webcast: Link

- date: 10/6 - 10/12
  title: Modeling and Estimation in Gentrification and COVID-19
  lab: Link
  webcast: Link

- date: 10/13 - 10/19
  title: Geospatial Analysis in Environmental Justice
  lab: Link
  webcast: Link

- date: 10/20 - 10/26
  title: NO LECTURE
  lab:
  webcast:

- date: 10/27 - 11/2
  title: Deep Learning in MRI Image Modeling
  lab: Link
  webcast: Link

- date: 11/3 - 11/9
  title: Language Modeling and Racial Bias in Public Policy
  lab: Link
  webcast: Link

- date: 11/10 - 11/16
  title: NO LECTURE
  lab:
  webcast:

- date: 11/17 - 11/23
  title: Computer Vision and Disaster Response
  lab: Link
  webcast: Link

- date: 11/24 - 12/6
  title: NO LECTURE
  lab:
  webcast:

- date: 12/7 - 12/13
  title: NO LECTURE
  lab:
  webcast:
