- date: 9/19
  title: NO LECTURE

- date: 9/24
  title: Introduction to Data Science, Social Good, Python Visualization
  lab:
    link: https://drive.google.com/drive/folders/1uYz7rWNK0UGxt1_g7M_bEHNP62iu3c1f?usp=sharing
    title: Assets
  webcast:
      link: https://drive.google.com/file/d/1vkS4fqZFay-yMA1jtJ0tezgclGeIKU0f/view?usp=sharing
      title: Webcast

- date: 10/2
  title: Linear Regression and Regularization
  lab:
    link: https://drive.google.com/drive/folders/1hxbwB2EtQNcpe3E9o8mbd2nQU7AunOFu?usp=sharing
    title: Assets
  webcast:
      link: https://drive.google.com/file/d/1vjnoGb1O33ofWE9uMBmM0k1hl2mOZaf6/view?usp=sharing
      title: Webcast

- date: 10/6
  title: Modeling and Estimation in Gentrification and COVID-19

- date: 10/15
  title: Geospatial Analysis in Environmental Justice

- date: 10/22
  title: NO LECTURE

- date: 10/29
  title: Language Modeling and Racial Bias in Public Policy

- date: 11/5
  title: Deep Learning in MRI Image Modeling

- date: 11/12
  title: NO LECTURE

- date: 11/19
  title: Computer Vision and Disaster Response

- date: 11/26
  title: NO LECTURE

- date: 12/9
  title: NO LECTURE
