- date: 9/17
  title: NO LECTURE

- date: 9/24
  title: Introduction to Data Science, Social Good, Python Visualization
  lab:
    link: https://drive.google.com/drive/folders/1uYz7rWNK0UGxt1_g7M_bEHNP62iu3c1f?usp=sharing
    title: Assets
  webcast:
      link: https://drive.google.com/file/d/1vkS4fqZFay-yMA1jtJ0tezgclGeIKU0f/view?usp=sharing
      title: Webcast

- date: 10/2
  title: Linear Regression and Regularization
  lab:
    link: https://drive.google.com/drive/folders/1hxbwB2EtQNcpe3E9o8mbd2nQU7AunOFu?usp=sharing
    title: Assets
  webcast:
      link: https://drive.google.com/file/d/1vjnoGb1O33ofWE9uMBmM0k1hl2mOZaf6/view?usp=sharing
      title: Webcast

- date: 10/9
  title: Modeling & Estimation (Gentrification/COVID19)
  lab:
    link: https://drive.google.com/drive/folders/1e5nXcIxb3l0M6dYbgNcW9dIBKGUWpQaF?usp=sharing
    title: Assets
  webcast:
      link: https://drive.google.com/file/d/1FVChpxNFEC1pjyS1Vx7ZSZY8uAijPuNa/view?usp=sharing
      title: Webcast

- date: 10/16
  title: Intro to Pandas
  lab:
    link: https://drive.google.com/drive/folders/15XfJPNPgX_x3oFUs3oTZMXckDJT5qdqN?usp=sharing
    title: Assets
  webcast:
      link: https://berkeley.zoom.us/rec/play/JJP0HAPjnMv_zFKqrrVbuR0dOtdVEbQrMOqtWqG5frluCFtzt3RZI3hv8G1ha1XXxVji-pUbKENPbw47.WXscG_a_8Eq8xsdr
      title: Webcast

- date: 10/22
  title: NO LECTURE

- date: 10/30
  title: Geospatial Analysis (Environmental Justice)
  lab:
    link: https://drive.google.com/drive/u/1/folders/1V93GKYp9ta_W7PdGk3urqD4JqAL1bK-Q?safe=active
    title: Assets
  webcast:
    link: https://berkeley.zoom.us/rec/play/MsPdnWrhme6J3vhvktGPnsQPxCXF5J_RgStmtfzkbTrKDgthbGL-Gs4nnk8mPWIVJy84vUYT0wr4qhZ1.jiUZyimQ2XFJa-Xc
    title: Webcast

- date: 11/6
  title: Intro to Machine Learning

- date: 11/12
  title: NO LECTURE

- date: 11/20
  title: Language Modeling (Racial Bias in Public Policy)

- date: 11/26
  title: NO LECTURE

- date: 12/9
  title: NO LECTURE
